no-resolv
port=0
dhcp-authoritative
log-dhcp
interface=br-vlan10
# bind-dynamic: the bridge may appear after dnsmasq starts
bind-dynamic
dhcp-range=set:vlan10,10.10.10.50,10.10.10.250,255.255.255.0,12h
dhcp-option=tag:vlan10,3,10.10.10.1
dhcp-option=tag:vlan10,6,10.10.10.1
